-- Seed: historische data uit Excel (gegenereerd 2026-07-15)
-- Draai NA schema.sql. Idempotent: bestaande rijen worden overschreven.

insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P001','Rijnbeek & Zoon B.V','Ilko Andreev','Kas medewerker',5187.0,'2026-03-23','2026-04-28',7,1,14,0,'2026-06-16','Gestopt buiten garantie - geen vervanging','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P002','Rijnbeek & Zoon B.V','Joanna Czaja','Kas medewerker',5187.0,'2026-03-30','2026-04-28',7,1,14,0,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P003','Noord-Europees Wijnopslag Bedrijf B.V.','Hairil Karim','Verladings Operator',8942.4,'2026-04-22','2026-04-22',1,1,14,2,'2026-05-21','VERVANGING LEVEREN (kandidaat gestopt)','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P004','Thermon Europe B.V.','Shifaz Salamat','Assemblage Monteur',8644.32,'2026-04-28','2026-04-28',1,1,14,0,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P005','KSB Industries B.V','Manu Wattimury','Assemlage Monteur',8412.16,'2026-04-29','2026-04-29',1,1,30,0,'2026-05-29','Gestopt buiten garantie - geen vervanging','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P006','Starcuisine','Filip Swiatek','Lijnoperator',10365.66,'2026-05-06','2026-05-06',2,3,14,0,'2026-05-30','Gestopt buiten garantie - geen vervanging','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P007','KSB Industries B.V','Mohammed Soleban','Assemblage Monteur',8165.0,'2026-05-18','2026-05-18',1,1,30,1,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P008','De Gier B.V','Krystian Dacyna','Spuiter',6500.0,'2026-03-25','2026-03-25',1,1,14,1,'2026-04-14','VERVANGING LEVEREN (kandidaat gestopt)','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P009','De Gier B.V','Ciprian - Andrei Gorea','Assemblage Monteur',6500.0,'2026-06-01','2026-06-01',1,1,14,1,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P010','Henri B.V','Fikret Hopic','Lijnoperator',8926.36,'2026-06-04','2026-06-04',1,1,14,1,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P011','Starcuisine','Mayura Fleming','Productiemedewerker',9442.24,'2026-06-05','2026-06-05',2,3,14,0,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P012','Starcuisine','Radjwantie Doerga','Lijnoperator',10220.68,'2026-06-05','2026-06-06',2,3,14,0,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P013','Starcuisine','Eugene Pita','Kok',8980.0,'2026-06-05','2026-06-05',2,3,14,0,'2026-06-26','Gestopt buiten garantie - geen vervanging','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P014','Rijnbeek & Zoon B.V','Anna Jarosz','Kas medewerker',6242.75,'2026-05-11','2026-06-11',7,1,14,0,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P015','Henri B.V','Kees Jorna','Kok',9576.97,'2026-06-11','2026-06-11',1,1,14,1,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P016','Henri B.V','Maciej Pociecha','Lijnoperator',9303.49,'2026-06-15','2026-06-15',1,1,14,1,null,'Garantie actief tot 15-07','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P017','Starcuisine','Snezana Stojilkovic','Productiemedewerker',9322.66,'2026-06-16','2026-06-16',2,3,14,0,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P018','Henri B.V','Adib Kamali','Productiemedewerker',8592.54,'2026-06-17','2026-06-17',1,1,14,1,null,'Garantie actief tot 17-07','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P019','Starcuisine','Dariusz Kilanowski','Lijnoperator',10221.0,'2026-06-22','2026-06-22',2,3,14,0,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P020','Starcuisine','Ayse Cecik','Productiemedewerker',9203.34,'2026-06-19','2026-06-19',2,3,14,0,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P021','Starcuisine','Sirjoe Anyaoha','Kok',8661.59,'2026-06-23','2026-06-23',2,3,14,0,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P024','Rijnbeek & Zoon B.V','Jordi Dekker','Meewerken voorman',5916.0,'2026-06-24','2026-08-06',7,1,14,0,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P025','Starcuisine','Azra Cekic','Productiemedewerker',8319.08,'2026-06-26','2026-06-26',2,3,14,0,'2026-07-03','Gestopt buiten garantie - geen vervanging','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P026','Starcuisine','Hasan Liban','Productiemedewerker',9582.14,'2026-06-26','2026-06-26',2,3,14,0,null,'Garantie verlopen','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;
insert into fin_placements (id,klant,kandidaat,functie,fee_excl,contract_datum,eerste_factuurdatum,aantal_termijnen,maanden_tussen,betaaltermijn_dgn,garantie_mnd,gestopt_op,garantie_note,bron) values ('P027','Whisk B.V','Michal Ostrowski','Logistiek medewerker',10432.8,'2026-06-30','2026-07-14',1,1,14,2,null,'Garantie actief tot 30-08','excel')
  on conflict (id) do update set klant=excluded.klant, kandidaat=excluded.kandidaat, functie=excluded.functie, fee_excl=excluded.fee_excl, contract_datum=excluded.contract_datum, eerste_factuurdatum=excluded.eerste_factuurdatum, aantal_termijnen=excluded.aantal_termijnen, maanden_tussen=excluded.maanden_tussen, betaaltermijn_dgn=excluded.betaaltermijn_dgn, garantie_mnd=excluded.garantie_mnd, gestopt_op=excluded.gestopt_op, garantie_note=excluded.garantie_note, bron=excluded.bron;

insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P001',1,741.0,'2026-04-28','betaald','2026-04-28',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P001',2,741.0,'2026-05-28','betaald','2026-05-28',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P001',3,741.0,'2026-06-28','gefactureerd','2026-06-30',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P001',4,741.0,'2026-07-28','vervallen',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P001',5,741.0,'2026-08-28','vervallen',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P001',6,741.0,'2026-09-28','vervallen',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P001',7,741.0,'2026-10-28','vervallen',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P002',1,741.0,'2026-04-28','betaald','2026-04-28',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P002',2,741.0,'2026-05-28','betaald','2026-05-28',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P002',3,741.0,'2026-06-28','gefactureerd','2026-06-30',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P002',4,741.0,'2026-07-28','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P002',5,741.0,'2026-08-28','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P002',6,741.0,'2026-09-28','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P002',7,741.0,'2026-10-28','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P003',1,8942.4,'2026-04-22','betaald','2026-04-22',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P004',1,8644.32,'2026-04-28','betaald','2026-04-28',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P005',1,8412.16,'2026-04-29','betaald','2026-04-29',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P006',1,5182.83,'2026-05-06','betaald','2026-05-06',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P006',2,5182.83,'2026-08-06','vervallen',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P007',1,8165.0,'2026-05-18','betaald','2026-05-18',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P008',1,6500.0,'2026-03-25','betaald','2026-03-25',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P009',1,6500.0,'2026-06-01','betaald','2026-06-01','2026-06-15')
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P010',1,8926.36,'2026-06-04','betaald','2026-06-04','2026-06-18')
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P011',1,4721.12,'2026-06-05','betaald','2026-06-05','2026-06-19')
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P011',2,4721.12,'2026-09-05','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P012',1,5110.34,'2026-06-06','betaald','2026-06-06','2026-06-20')
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P012',2,5110.34,'2026-09-06','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P013',1,4490.0,'2026-06-05','betaald','2026-06-05','2026-06-19')
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P013',2,4490.0,'2026-09-05','vervallen',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P014',1,891.82,'2026-06-11','betaald','2026-06-05','2026-06-25')
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P014',2,891.82,'2026-07-11','gefactureerd','2026-07-11',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P014',3,891.82,'2026-08-11','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P014',4,891.82,'2026-09-11','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P014',5,891.82,'2026-10-11','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P014',6,891.82,'2026-11-11','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P014',7,891.83,'2026-12-11','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P015',1,9576.97,'2026-06-11','betaald','2026-06-11',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P016',1,9303.49,'2026-06-15','betaald','2026-06-15',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P017',1,4661.33,'2026-06-16','betaald','2026-06-16',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P017',2,4661.33,'2026-09-16','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P018',1,8592.54,'2026-06-17','betaald','2026-06-18',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P019',1,5110.5,'2026-06-22','gefactureerd',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P019',2,5110.5,'2026-09-22','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P020',1,4601.67,'2026-06-19','betaald','2026-06-19',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P020',2,4601.67,'2026-09-19','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P021',1,4330.8,'2026-06-23','betaald','2026-06-23',null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P021',2,4330.79,'2026-09-23','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P024',1,845.14,'2026-08-06','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P024',2,845.14,'2026-09-06','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P024',3,845.14,'2026-10-06','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P024',4,845.14,'2026-11-06','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P024',5,845.14,'2026-12-06','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P024',6,845.14,'2027-01-06','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P024',7,845.16,'2027-02-06','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P025',1,4159.54,'2026-06-26','betaald',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P025',2,4159.54,'2026-09-26','vervallen',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P026',1,4791.07,'2026-06-26','betaald',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P026',2,4791.07,'2026-09-26','te_factureren',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
insert into fin_installments (placement_id,termijn_nr,bedrag_excl,geplande_datum,status,factuurdatum,betaaldatum) values ('P027',1,10432.8,'2026-07-14','gefactureerd',null,null)
  on conflict (placement_id, termijn_nr) do update set bedrag_excl=excluded.bedrag_excl, geplande_datum=excluded.geplande_datum, status=excluded.status, factuurdatum=excluded.factuurdatum, betaaldatum=excluded.betaaldatum;
